#!/usr/bin/env python3
"""
Test the 'give insights' question to verify multi-query detection
"""

import sys
sys.path.insert(0, '/Volumes/Extreme SSD/code/sql schema')

from src.core.sql_generator import SQLGenerator
from src.core.database import DatabaseManager

# Initialize components
db_path = "data/database/airline_company.db"
db_manager = DatabaseManager(db_path)
sql_gen = SQLGenerator(db_manager)

# Test question
question = "give interesting insights from the data"

print("=" * 70)
print(f"Question: {question}")
print("=" * 70)

# Check multi-query detection
needs_multi = sql_gen.needs_multi_query(question)
print(f"\nneeds_multi_query(): {needs_multi}")

if needs_multi:
    print("\n⚠️  WARNING: This should NOT trigger multi-query!")
    print("   'give insights' is NOT a comparison question")
    print("   Expected: False, Got: True")
else:
    print("\n✅ Correct: Single query path (UNION ALL is fine)")
    print("   This is a single complex query, not a multi-query plan")

print("\n" + "=" * 70)
print("Explanation:")
print("=" * 70)
print("""
UNION ALL query = Single Query (Correct ✓)
  - One SQL statement with multiple SELECT clauses
  - Executes as a single database operation
  - Generated by Gemini/Groq in one go
  - Fast execution (<100ms)

Multi-Query Plan = Multiple Queries (For comparisons only)
  - Separate SQL queries with dependencies
  - Each query runs independently
  - Results combined with CTEs
  - Used for: "Compare IT vs Sales"
  
For "give insights", UNION ALL is the RIGHT approach!
""")
